### ISSUE TITLE
Warnings from CoffeeLint ignored

### ISSUE THREAD

**Issue by dpuscher** [codeclimate/codeclimate-coffeelint#23]
Currently warnings from CoffeeLint are ignored (by using the `-q` parameter). Is this expected behaviour? I would rather like to have the warnings also to be displayed in CodeClimate

**Comment by maxjacobson** [comment]
Hi @dpuscher, thanks for opening this issue.

I see your point -- it looks like many coffeelint checks won't be included because we pass the `-q` parameter and this can affect how useful our coffeelint engine is. I also see it's been that way from [our very first commit](https://github.com/codeclimate/codeclimate-coffeelint/commit/b99a1744c1976c105165e4f45f81c09531d4d5c8#diff-a4e6becf1a8a539b43b9d662e27d659bR12) so I don't have a ton of context on the decision.

One thing you can certainly do today is amend your `coffeelint.json` and change the individual checks from `warn` to `error` that you want to be included on Code Climate.

Change

```
"no_debugger": {
    "level": "warn",
    "console": false
  },
```

to:

```
"no_debugger": {
    "level": "error",
    "console": false
  },
```

I tend to agree that we should default to including all checks, and let users change the level to `ignore` that they'd like to ignore.

Would you like to make such a PR?
